# The URL the site will be built for
base_url = "https://yegcsharpdev.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The site title
title = "YEGCSharpDev"

# The site description
description = "Edmonton C# Developers Group"


